### ISSUE TITLE
Crash when specifying existing --star_index using star aligner

### ISSUE THREAD

**Issue by ffmmulder** [nf-core/scrnaseq#277]
### Description of the bug

When specifying an existing STAR index using the --star_index parameter the pipeline crashes and gives the following error: 

```
Missing process or function map([Script_396cc086$_runScript_closure1$_closure2$_closure5@20bc6f4d])

 -- Check script '/hpc/ubec/tools/pipelines/nfcore/scrnaseq/./workflows/scrnaseq.nf' at line: 170 or see '.nextflow.log' file for more 
details
```

This is because in this case the ch_star_index is defined as a file instead of a tuple which is expected by the starsolo subworkflow (and which is also returned by STAR_GENOMEGENERATE in case no existing star genome is specified).

scrnaseq.nf:
```
ch_star_index = params.star_index ? file(params.star_index) : []
```
This can be fixed by adjust the line above to:
```
ch_star_index = params.star_index ? Channel.fromPath(params.star_index).map{f -> [[id:f.baseName], f] } : []
```

### Command used and terminal output

```console
Command

nextflow run /path/to/nfcore/scrnaseq/main.nf \
--input /path/to/amplesheet.csv \
--star_index /path/to/reference/star \
--fasta /path/to/fasta.fna \
--gtf /path/to/reference.gtf \
--protocol 10XV3 \
--aligner star \
--outdir /path/to/output
```
Output:
```
N E X T F L O W  ~  version 23.04.2
WARN: It appears you have never run this project before -- Option `-resume` is ignored
Launching `/hpc/ubec/tools/pipelines/nfcore/scrnaseq/main.nf` [mighty_pasteur] DSL2 - revision: bd078e3da5
[-        ] process > NFCORE_SCRNASEQ:SCRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK -
Missing process or function map([Script_396cc086$_runScript_closure1$_closure2$_closure5@20bc6f4d])

 -- Check script '/hpc/ubec/tools/pipelines/nfcore/scrnaseq/./workflows/scrnaseq.nf' at line: 170 or see '.nextflow.log' file for more details

```
```


### Relevant files

_No response_

### System information

* Nextflow version: 23.04.2
* Hardware: HPC
* Executor: Slurm
* Container engine: singularity
* OS: CentOS8 Rocky
* version of nf-core/scrnaseq: 2.4.1

**Comment by grst** [comment]
Thanks for reporting!

Would you like to submit a PR with the fix?

**Comment by ffmmulder** [comment]
Sure, currently doing a small test to make sure all works fine but looks ok... will see if I can do it later today!

**Comment by pinin4fjords** [comment]
I'm still seeing this behaviour in 2.6.0 - did this fix not work?

**Comment by Billsfriend** [comment]
I met similar problem in 2.6.0. Setting --star_index with "/path/to/folder/" will end up with:
```
ERROR ~ ERROR: Validation of pipeline parameters failed!

 -- Check 'ye.1.log' file for details
The following invalid input values have been detected:

* --star_index: '/home/gjsx/append-ssd/work/star_index/' is not a file, but a directory (/home/gjsx/append-ssd/work/star_index/)

 -- Check script '/home/gjsx/.nextflow/assets/nf-core/scrnaseq/./workflows/../subworkflows/local/utils_nfcore_scrnaseq_pipeline/../../nf-core/utils_nfvalidation_plugin/main.nf' at line: 57 or see 'ye.1.log' file for more details
```

**Comment by grst** [comment]
> I'm still seeing this behaviour in 2.6.0 - did this fix not work?

I don't think anyone made the PR up to now.

**Comment by j-andrews7** [comment]
This is also a problem for all other aligners as far as I can tell.

**Comment by allumik** [comment]
I applied the fix above, the star_index folder did not give any errors and STAR worked. But surprisingly, it only processed the first sample out of nine, even when it produced fastqc reports for all nine. Reverting this fix and letting the pipeline generate its own index made the pipeline work again as expected.

Haven't had time to go through the code to find an explanation though.

**Comment by grst** [comment]
Good catch, it should be
```
ch_star_index = params.star_index ? Channel.fromPath(params.star_index).map{f -> [[id:f.baseName], f] }.collect() : []
```

The `.collect()` converts it into a value channel that is then reused across processes.

**Comment by grst** [comment]
should be fixed in dev, LMK if there are still issues.

**Comment by esrice** [comment]
I'm still getting this error in 2.7.1 😦:

```
Missing process or function map([Script_7fdd45e8fb4b4830$_runScript_closure1$_closure2$_closure5@44572f11])
```
Only happens when I specify an existing star index.
